C = {  # code: (country name, [ (id, city, tz, aliases) ])
 "KR":("South Korea",[("seoul","Seoul","Asia/Seoul","korea 서울"),("busan","Busan","Asia/Seoul","부산")]),
 "JP":("Japan",[("tokyo","Tokyo","Asia/Tokyo","東京"),("osaka","Osaka","Asia/Tokyo","")]),
 "CN":("China",[("beijing","Beijing","Asia/Shanghai","peking"),("shanghai","Shanghai","Asia/Shanghai",""),("shenzhen","Shenzhen","Asia/Shanghai","")]),
 "HK":("Hong Kong",[("hong-kong","Hong Kong","Asia/Hong_Kong","")]),
 "TW":("Taiwan",[("taipei","Taipei","Asia/Taipei","")]),
 "SG":("Singapore",[("singapore","Singapore","Asia/Singapore","")]),
 "ID":("Indonesia",[("jakarta","Jakarta","Asia/Jakarta",""),("bali","Bali (Denpasar)","Asia/Makassar","denpasar")]),
 "MY":("Malaysia",[("kuala-lumpur","Kuala Lumpur","Asia/Kuala_Lumpur","kl")]),
 "TH":("Thailand",[("bangkok","Bangkok","Asia/Bangkok","")]),
 "VN":("Vietnam",[("ho-chi-minh-city","Ho Chi Minh City","Asia/Ho_Chi_Minh","saigon"),("hanoi","Hanoi","Asia/Ho_Chi_Minh","")]),
 "PH":("Philippines",[("manila","Manila","Asia/Manila","")]),
 "IN":("India",[("new-delhi","New Delhi","Asia/Kolkata","delhi"),("mumbai","Mumbai","Asia/Kolkata","bombay"),("bengaluru","Bengaluru","Asia/Kolkata","bangalore")]),
 "PK":("Pakistan",[("karachi","Karachi","Asia/Karachi","")]),
 "BD":("Bangladesh",[("dhaka","Dhaka","Asia/Dhaka","")]),
 "NP":("Nepal",[("kathmandu","Kathmandu","Asia/Kathmandu","")]),
 "LK":("Sri Lanka",[("colombo","Colombo","Asia/Colombo","")]),
 "MN":("Mongolia",[("ulaanbaatar","Ulaanbaatar","Asia/Ulaanbaatar","")]),
 "AE":("United Arab Emirates",[("dubai","Dubai","Asia/Dubai","uae"),("abu-dhabi","Abu Dhabi","Asia/Dubai","uae")]),
 "SA":("Saudi Arabia",[("riyadh","Riyadh","Asia/Riyadh","")]),
 "QA":("Qatar",[("doha","Doha","Asia/Qatar","")]),
 "IL":("Israel",[("tel-aviv","Tel Aviv","Asia/Jerusalem","jerusalem")]),
 "TR":("Turkey",[("istanbul","Istanbul","Europe/Istanbul","turkiye")]),
 "EG":("Egypt",[("cairo","Cairo","Africa/Cairo","")]),
 "ZA":("South Africa",[("johannesburg","Johannesburg","Africa/Johannesburg",""),("cape-town","Cape Town","Africa/Johannesburg","")]),
 "NG":("Nigeria",[("lagos","Lagos","Africa/Lagos","")]),
 "KE":("Kenya",[("nairobi","Nairobi","Africa/Nairobi","")]),
 "MA":("Morocco",[("casablanca","Casablanca","Africa/Casablanca","")]),
 "GB":("United Kingdom",[("london","London","Europe/London","uk england britain"),("manchester","Manchester","Europe/London","uk"),("edinburgh","Edinburgh","Europe/London","scotland uk")]),
 "IE":("Ireland",[("dublin","Dublin","Europe/Dublin","")]),
 "FR":("France",[("paris","Paris","Europe/Paris","")]),
 "DE":("Germany",[("berlin","Berlin","Europe/Berlin",""),("munich","Munich","Europe/Berlin","münchen"),("frankfurt","Frankfurt","Europe/Berlin","")]),
 "NL":("Netherlands",[("amsterdam","Amsterdam","Europe/Amsterdam","holland")]),
 "BE":("Belgium",[("brussels","Brussels","Europe/Brussels","")]),
 "ES":("Spain",[("madrid","Madrid","Europe/Madrid",""),("barcelona","Barcelona","Europe/Madrid","")]),
 "PT":("Portugal",[("lisbon","Lisbon","Europe/Lisbon","lisboa")]),
 "IT":("Italy",[("rome","Rome","Europe/Rome","roma"),("milan","Milan","Europe/Rome","milano")]),
 "CH":("Switzerland",[("zurich","Zurich","Europe/Zurich","geneva")]),
 "AT":("Austria",[("vienna","Vienna","Europe/Vienna","wien")]),
 "SE":("Sweden",[("stockholm","Stockholm","Europe/Stockholm","")]),
 "NO":("Norway",[("oslo","Oslo","Europe/Oslo","")]),
 "DK":("Denmark",[("copenhagen","Copenhagen","Europe/Copenhagen","")]),
 "FI":("Finland",[("helsinki","Helsinki","Europe/Helsinki","")]),
 "PL":("Poland",[("warsaw","Warsaw","Europe/Warsaw","")]),
 "CZ":("Czechia",[("prague","Prague","Europe/Prague","czech republic")]),
 "HU":("Hungary",[("budapest","Budapest","Europe/Budapest","")]),
 "GR":("Greece",[("athens","Athens","Europe/Athens","")]),
 "RO":("Romania",[("bucharest","Bucharest","Europe/Bucharest","")]),
 "UA":("Ukraine",[("kyiv","Kyiv","Europe/Kyiv","kiev")]),
 "RU":("Russia",[("moscow","Moscow","Europe/Moscow","")]),
 "US":("United States",[("new-york","New York","America/New_York","usa nyc america"),("washington-dc","Washington, D.C.","America/New_York","usa"),("boston","Boston","America/New_York","usa"),("miami","Miami","America/New_York","usa"),("atlanta","Atlanta","America/New_York","usa"),("chicago","Chicago","America/Chicago","usa"),("dallas","Dallas","America/Chicago","usa texas"),("houston","Houston","America/Chicago","usa texas"),("denver","Denver","America/Denver","usa"),("phoenix","Phoenix","America/Phoenix","usa arizona"),("los-angeles","Los Angeles","America/Los_Angeles","usa la"),("san-francisco","San Francisco","America/Los_Angeles","usa sf bay area silicon valley"),("seattle","Seattle","America/Los_Angeles","usa"),("honolulu","Honolulu","Pacific/Honolulu","usa hawaii")]),
 "CA":("Canada",[("toronto","Toronto","America/Toronto",""),("montreal","Montreal","America/Toronto",""),("vancouver","Vancouver","America/Vancouver","")]),
 "MX":("Mexico",[("mexico-city","Mexico City","America/Mexico_City","cdmx")]),
 "BR":("Brazil",[("sao-paulo","São Paulo","America/Sao_Paulo","sao paulo"),("rio-de-janeiro","Rio de Janeiro","America/Sao_Paulo","rio")]),
 "AR":("Argentina",[("buenos-aires","Buenos Aires","America/Argentina/Buenos_Aires","")]),
 "CL":("Chile",[("santiago","Santiago","America/Santiago","")]),
 "CO":("Colombia",[("bogota","Bogotá","America/Bogota","bogota")]),
 "PE":("Peru",[("lima","Lima","America/Lima","")]),
 "AU":("Australia",[("sydney","Sydney","Australia/Sydney",""),("melbourne","Melbourne","Australia/Melbourne",""),("brisbane","Brisbane","Australia/Brisbane",""),("perth","Perth","Australia/Perth","")]),
 "NZ":("New Zealand",[("auckland","Auckland","Pacific/Auckland","wellington")]),
}
